name: Build and Publish PackageA
run-name: ${{ github.actor }} has modified packageA
on: 
 push:
  branches:
    - main
  paths:
    - PackageA/**

jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v